mgrs_tiles = [
    '28WET',
    '04QGE',
    '26WPT',
    '04QEH',
    '27WVP',
    '04QEK',
    '04QBM',
    '03QZD',
    '28WEU',
    '05QLC',
    '04QFF',
    '04QDK',
    '28WDU',
    '03QZF',
    '04QFH',
    '04QCK',
    '27VWK',
    '27WVQ',
    '04QCH',
    '28WEV',
]

field_names = [
    'The Cherries',
    'Mill Bank',
    'Lake View',
    'Littleworth Villa',
    'Applelands',
    'Lakeside',
    'Orchard View',
    'Cherrylands',
    'Pauline\'s Gates',
    'Apple Gates',
    'Orchardside',
    'Lakeways',
    'Cherry Barn',
    'The Apples',
    'The Old Bakery',
    'Rat\'s Gates',
    'Breezy Barn',
    'Blonde Farm',
    'Norfolk',
    'Blenheim',
    'Hillside',
    'Primrose',
    'Vicarage',
    'Napier',
    'The Pines',
    'The Oval',
    'Beaufort',
    'Belgrave',
    'Cherry',
    'Osborne',
    'Pinewood',
    'Coppice',
    'Rowan',
    'Henry',
    'Wentworth',
    'Walker',
    'Crown',
    'Jubilee',
    'Oak Tree',
    'Priory Gardens',
    'Campion',
    'The Mews',
    'Quarry',
    'Nursery',
    'Love',
    'Hornbeam',
    'Manor Gardens',
    'Walnut',
    'Thornton',
    'Roman',
    'Sunnyside',
    'Mary',
    'Foxglove',
    'Brookside',
    'Woodhouse',
    'Laurel',
    'Victoria Terrace',
    'Portland',
    'Station',
    'West View',
    'Manor',
    'Martin',
    'Queen\'s',
    'Woodlands',
    'Bishops',
    'Second',
    'Church Hill',
    'Lichfield',
    'Abbey',
    'Brook',
    'Portland',
    'River View',
    'St John\'s',
    'Castle',
    'Graham',
    'Hamilton',
    'St Marys',
    'Mount Pleasant',
    'Grange',
    'Western',
    'Ash',
    'Central',
    'The Limes',
    'Essex',
    'Wilson',
    'Balmoral',
    'The Grove',
    'School Hill',
    'Marsh',
    'Cliff',
    'Woodside',
    'Ridgeway',
    'Highfield',
    'Old',
    'Middleton',
    'Ash Grove',
    'Dale',
    'Bull',
    'Dudley',
    'Hillside',
    'Bond',
    'Greenfield',
    'Cedar Grove',
    'Manor Court',
    'Byron',
    'Newton',
    'Hawthorn',
    'West',
    'Windsor',
    'Laurel',
    'St Peter\'s',
    'Riverside',
    'Alexandra',
    'Derwent',
    'Boundary',
    'Bell',
    'Clifton',
    'Lansdowne',
]
